name: sector-coupled-euro-calliope
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.8
    - pycountry=19.8.18
    - snakemake-minimal=6.15.5
    - tabulate=0.8.10  # fixes incompatibility of tabulate 0.9 and snakemake 6.1.1. Should be fixed after snakemake 7.15.2
