euro-calliope:
    parameters:
        jrc-biofuel: #from [#Ruiz Castello et al:2015]
            potential-year: "2050"
            cost-year: "2050"
        biofuel-efficiency: 0.45
        nuclear-capacity-year: 2050
