data-sources:
    capacity-factors: https://zenodo.org/record/6559895/files/{filename}?download=1
    nuts: https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2/nuts/geojson/NUTS_RG_01M_{nuts_year}_4326.geojson
    potentials: https://zenodo.org/record/6600619/files/raw-potentials.zip?download=1
    statistical-units-to-custom-regions:
        ehighways: ../data/statistical_units_to_ehighways_regions.csv
root-directory: .
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/euro-calliope/
    local-results-dir: build/cluster
scaling-factors:
    power: 0.00001 # from MW to 100 GW
    area: 0.0001 # from km to 10000 km2
    monetary: 0.000000001  # from EUR to 1000 Mio EUR
    distance: 1
    energy: 10 # from TW(h) to 100 GW(h)
    transport: 0.01  # from Mio km to 100 Mio km
    co2: 0.0001  # from t to 10 kt
    co2_cost:  0.000001  # from t to Mt
capacity-factors:
    trim-ninja-timeseries: false
parameters:
    jrc-biofuel: #from [#Ruiz Castello et al:2015]
        scenario: "medium"
        potential-year: "2050"
        cost-year: "2050"
    biofuel-efficiency: 0.45
    nuclear-capacity-year: 2050
    transport:
        efficiency:  # MWh / mio km 25th percentile efficiency of all countries in 2015 [JRC_IDEES]
            hdv:
                diesel: 5140
                electricity: 3248  # based on buses
            ldv:
                diesel: 855
                electricity: 480
            motorcycle:
                diesel: 419
                electricity: 200  # based on passenger car electrical efficiency scaled by relative diesel efficiency
            bus:
                diesel: 6057
                electricity: 3248
            passenger_car:
                diesel: 675
                electricity: 324

    heat-end-use:
        carriers: heat  # also could be [space-heat, water-heat]
        space_heat_techs:
            carnot_performance: 0.36  # [Nouvel_2015]
            gas_eff: 0.97  # [DEA_2016], but 70-80% according to [Qu_2014]
            oil_eff: 0.9  # [DEA_2016], but 0.63 according to [martin_2014]
            solid_fossil_eff: 0.8 # Assume same as biofuel
            biofuel_eff: 0.8  # [mermoud_2015] [Chandrasekaran_2013] [DEA_2016]
            solar_thermal_eff: 1  # Eurostat energy balances method
            electricity_eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
            space_heat_temp: 36  # degrees C [Nouvel_2015]
            hp_cop: 3.5
        water_heat_techs:
            gas_eff: 0.97  # [DEA_2016], but 70-80% according to [Qu_2014]
            oil_eff: 0.9  # [DEA_2016], but 0.63 according to [martin_2014]
            solid_fossil_eff: 0.8 # Assume same as biofuel
            biofuel_eff: 0.8  # [mermoud_2015] [Chandrasekaran_2013] [DEA_2016]
            solar_thermal_eff: 1  # Eurostat energy balances method
            electricity_eff: 1  # must be 1 for the time being (we assume 1 -> 1 electricity -> heat conversion)
            water_heat_temp: 52  # degrees C [Nouvel_2015]
            hp_cop: 3.5
        cooking_techs:
            gas_eff: 0.28  # [Karunanithy_2016]
            oil_eff: 0.28  # [Karunanithy_2016] assuming oil == gas efficiency
            solid_fossil_eff: 0.15 # [Ramanathan_1994] scaled down 60%, based on values calculated by [Karunanithy_2016]
            biofuel_eff: 0.1 #  [Ramanathan_1994] scaled down 60%, based on values calculated by [Karunanithy_2016]
            electricity_eff: 0.5  # [Karunanithy_2016] based on 2/3 40% efficient direct electric, 1/3 70% efficient induction
        heat_pump_ratio:  # see https://www.ehpa.org/fileadmin/red/07._Market_Data/2018/2018-05-06_Heat_Pumps_in_Europe_2019.pdf and https://www.ehpa.org/fileadmin/red/07._Market_Data/Heat_Pumps_in_Europe_2017.pdf
            ashp: 0.91
            gshp: 0.09

sea-connections:
    continental: []
    national:
        - [ITA, GRC]
        - [EST, FIN]
        - [SWE, LTU]
        - [SWE, POL]
        - [DNK, SWE]
        - [SWE, DEU]
        - [NOR, DNK]
        - [NOR, DEU]
        - [NOR, NLD]
        - [NOR, GBR]
        - [FIN, SWE]
        - [GBR, FRA]
        - [GBR, BEL]
        - [GBR, NLD]
        - [GBR, IRL]
        - [GBR, ISL]
        # the following do not exist today
        - [GRC, CYP]
    regional:
        - [ESP.7_1, ESP.1_1] # Ceuta and Andalucia
        - [ESP.13_1, ESP.10_1] # Islas Baleares and Comunidad Valenciana
        - [FRA.5_1, ITA.16_1] # Corse and Toscana
        - [FRA.5_1, ITA.14_1] # Corse and Sardegna
        - [ITA.14_1, ITA.8_1] # Sardegna and Lazio
        - [ITA.4_1, ITA.15_1] # Calabria and Sicily
        - [ITA.2_1, GRC.5_1] # Apulia and Epirus and Western Macedonia
        - [GRC.7_1, GRC.4_1] # Peloponnese, Western Greece and the Ionian Islands and Crete
        - [GRC.3_1, GRC.1_1] # Attica and Aegean
        - [EST.1_1, FIN.4_1] # Harju and Southern Finland
        - [SWE.8_1, LTU.3_1] # Kalmar and Klaipedos
        - [SWE.8_1, SWE.4_1] # Kalmar and Gotland
        - [SWE.1_1, POL.11_1] # Blekinge and Pomorskie
        - [DNK.1_1, SWE.13_1] # Hovedstaden and Skåne
        - [SWE.13_1, DEU.15_1] # Skåne and Schleswig-Holstein
        - [DNK.4_1, DEU.8_1] # Sjælland and Mecklenburg-Vorpommern
        - [DNK.4_1, DNK.5_1] # Sjælland and Syddanmark
        - [DNK.3_1, SWE.21_1] # Nordjylland and Västra Götaland
        - [NOR.18_1, DNK.3_1] # Vest-Agder and Nordjylland
        - [NOR.18_1, DEU.15_1] # Vest-Agder and Schleswig-Holstein
        - [NOR.18_1, NLD.5_1] # Vest-Agder and Groningen
        - [NOR.13_1, GBR.1_1] # Rogaland and England
        - [FIN.5_1, SWE.16_1] # Western Finland and Uppsala
        - [GBR.1_1, FRA.7_1] # England and Hauts-de-France
        - [GBR.1_1, BEL.2_1] # England and Vlaanderen
        - [GBR.1_1, NLD.14_1] # England and Zuid-Holland
        - [GBR.4_1, IRL.17_1] # Wales and Meath
        - [GBR.3_1, GBR.2_1] # Scotland and Northern Ireland
        # the following do not exist today
        - [EST.7_1, EST.2_1] # Lääne and Hiiu
        - [EST.7_1, EST.12_1] # Lääne and Saare
        - [GBR.3_1, ISL.1_1]
        - [GRC.1_1, CYP.5_1] # Aegean and Paphos
        - [CYP.1_1, CYP.2_1] # Famagusta and Larnaca
    ehighways:
        - [ITA_3, ITA_6]
        - [ITA_6, FRA_15]
        - [ITA_2, FRA_15]
        - [ITA_4, ITA_5]
        - [ITA_3, MNE_1]
        - [ITA_2, HRV_1]
        - [ITA_4, ALB_1]
        - [ITA_4, GRC_1]
        - [CYP_1, GRC_2]
        - [EST_1, FIN_2]
        - [FIN_2, SWE_3]
        - [LTU_1, SWE_3]
        - [POL_5, SWE_4]
        - [NOR_1, GBR_4]
        - [GBR_4, GBR_6]
        - [GBR_3, IRL_1]
        - [FRA_8, IRL_1]
        - [FRA_9, GBR_1]
        - [FRA_9, GBR_1]
        - [FRA_13, GBR_1]
        - [BEL_1, GBR_1]
        - [NLD_1, GBR_1]
        - [NLD_1, NOR_1]
        - [DEU_1, NOR_1]
        - [DNK_1, DNK_2]
        - [DNK_1, NOR_1]
        - [DNK_1, SWE_3]
        - [DEU_1, SWE_4]
        # the following do not exist today
        - [GBR_5, ISL_1]
        - [GRC_2, CYP_1]
scope:
    temporal:
        first-year: 2010
        final-year: 2018
    spatial:
        countries:
            - "Austria"
            - "Belgium"
            - "Bulgaria"
            - "Croatia"
            - "Cyprus"
            - "Czech Republic"
            - "Denmark"
            - "Estonia"
            - "Finland"
            - "France"
            - "Germany"
            - "Greece"
            - "Hungary"
            - "Ireland"
            - "Italy"
            - "Latvia"
            - "Lithuania"
            - "Luxembourg"
            - "Netherlands"
            - "Poland"
            - "Portugal"
            - "Romania"
            - "Slovakia"
            - "Slovenia"
            - "Spain"
            - "Sweden"
            - "United Kingdom"
            - "Albania"
            - "Bosnia and Herzegovina"
            - "North Macedonia"
            - "Montenegro"
            - "Norway"
            - "Serbia"
            - "Switzerland"
            - "Iceland"
        bounds:
            x_min: -15.8 # in degrees east
            x_max: 37  # in degrees east
            y_min: 30  # in degrees north
            y_max: 75  # in degrees north

shapes:
    ehighways_disaggregated:
        Austria: nuts3
        Belgium: nuts0
        Bulgaria: nuts0
        Croatia: nuts0
        Cyprus: nuts0
        Czech Republic: nuts3
        Denmark: nuts3
        Estonia: nuts0
        Finland: nuts3
        France: nuts3
        Germany: nuts3
        Greece: nuts3
        Hungary: nuts0
        Ireland: nuts0
        Italy: nuts3
        Latvia: nuts0
        Lithuania: nuts0
        Luxembourg: nuts0
        Netherlands: nuts0
        Poland: nuts3
        Portugal: nuts3
        Romania: nuts3
        Slovakia: nuts0
        Slovenia: nuts0
        Spain: nuts3
        Sweden: nuts3
        United Kingdom: nuts3
        Albania: gadm0
        Bosnia and Herzegovina: gadm0
        North Macedonia: gadm0
        Montenegro: gadm0
        Norway: nuts3
        Serbia: gadm0
        Switzerland: nuts3
        Iceland: nuts0
    continental:
        Iceland: nuts0
    national:
        Iceland: nuts0
    regional:
        Iceland: gadm1
